USE knowyourcandidates;

INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (1,'Gaikwad,Shri Eknath Mahadeo','INC','Mumbai-South-Central(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (2,'Majumdar,Shri Prasanta Kumar','RSP','Balurghat (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (3,'Khaire,Shri Chandrakant Bhaurao','SS','Aurangabad (Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (4,'Khurshid,Shri Salman','INC','Farrukhabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (5,'Bhagora,Shri Tarachand','INC','Banswara(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (6,'Bwiswmuthiary,Shri Sansuma Khung','BPF','Kokrajhar(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (7,'Rajbhar,Shri Ramashankar','BSP','Salempur (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (8,'Singh,Smt. Meena','JD(U)','Arrah(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (9,'Patel,Shri Bal Kumar','SP','Mirzapur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (10,'Argal,Shri Ashok','BJP','Bhind(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (11,'Scindia,Shri Jyotiraditya Madhav','INC','Guna(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (12,'Nagpal,Shri Devendra','RLD','Amroha (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (13,'Singh,Shri Ratan','INC','Bharatpur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (14,'Azad,Shri Kirti (Jha)','BJP','Darbhanga(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (15,'Mukherjee,Shri Abhijit','INC','Jangipur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (16,'Roy,Dr. Arjun','JD(U)','Sitamarhi(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (17,'Singh,Shri Jaswant','BJP','Darjeeling(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (18,'Singh,Dr. Bhola','BJP','Nawada(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (19,'Ering,Shri Ninong','INC','Arunachal East(Arunachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (20,'Gulshan,Smt. Paramjit Kaur','SAD','Faridkot (Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (21,'Wakchaure ,Shri Bhausaheb','SS','Shirdi(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (22,'Khatri,Dr. Nirmal','INC','Faizabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (23,'Banerjee,Shri Kalyan','AITC','Serampore(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (24,'Wankhede,Shri Subhash Bapurao','SS','Hingoli(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (25,'Hooda,Shri Deepender Singh','INC','Rohtak(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (26,'Singh,Shri Kalyan','Ind.','Etah(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (27,'Joshi,Dr. Murli Manohar','BJP','Varanasi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (28,'Ram,Shri Purnmasi','JD(U)','Gopalganj(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (29,'Bairwa,Shri Khiladi Lal','INC','Karauli-Dholpur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (30,'Bauri,Smt. Susmita','CPI(M)','Bishnupur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (31,'Kora,Shri Madhu','Ind.','Singhbhum(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (32,'Singh,Shri Brijbhushan Sharan','SP','Kaiserganj(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (33,'Das,Shri Ram Sundar','JD(U)','Hajipur(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (34,'Katheria,Shri Premdas','SP','Etawah(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (35,'Soren,Shri Shibu','JMM','Dumka(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (36,'Meghwal,Shri Bharat Ram','INC','Ganganagar(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (37,'Marandi,Shri Babu Lal','JVM (P)','Kodarma(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (38,'Choudhury,Shri Abu Hasem Khan','INC','Maldaha Dakshin(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (39,'Moily,Dr.(Shri) M. Veerappa','INC','Chikkballapur(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (40,'Chowdhury,Shri Bansa Gopal','CPI(M)','Asansol (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (41,'Maken,Shri Ajay','INC','New Delhi (Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (42,'Panda,Shri Baijayant "Jay"','BJD','Kendrapara(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (43,'Kumar,Shri Kaushalendra','JD(U)','Nalanda(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (44,'Chauhan,Smt. Raj Kumari','BSP','Aligarh(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (45,'Yadav,Shri Arun Subhashchandra','INC','Khandwa(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (46,'Yadav,Smt. Dimple','SP','Kannauj(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (47,'Reddy,Shri Jaipal Sudini','INC','Chelvella (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (48,'Ajnala,Dr. Rattan Singh','SAD','Khadoor Sahib(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (49,'Patil,Shri Sanjay Dina','NCP','Mumbai-North-East(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (50,'Shekhawat,Shri Gopal Singh','INC','Rajsamand(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (51,'Mandal,Dr. Tarun','Ind.','Jaynagar(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (52,'Pandey,Shri Ravindra Kumar','BJP','Giridih(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (53,'Jardosh,Smt. Darshana Vikram','BJP','Surat(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (54,'Kumar,Shri Vishwa Mohan','JD(U)','Supaul(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (55,'Punia,Shri P.L.','INC','Barabanki(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (56,'Saha,Dr. Anup Kumar','CPI(M)','Bardhaman Purba(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (57,'Singh,Shri Rajiv Ranjan (Lalan)','JD(U)','Munger(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (58,'Manjhi,Shri Hari','BJP','Gaya(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (59,'Dubey,Shri Nishikant','BJP','Godda (Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (60,'Bajwa,Sardar Partap Singh','INC','Gurdaspur(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (61,'Alagiri,Shri M. K.','DMK','Madurai(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (62,'Katoch,Smt. Chandresh Kumari','INC','Jodhpur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (63,'Choudhary,Shri Bhudeo','JD(U)','Jamui (Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (64,'Gutha,Shri Sukender Reddy','INC','Nalgonda(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (65,'Singh,Chaudhary Lal','INC','Udhampur(Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (66,'Shivaramagouda,Shri','BJP','Koppal(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (67,'Yadav,Shri Dharmendra','SP','Badaun(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (68,'Meena,Shri Raghuvir Singh','INC','Udaipur (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (69,'Venugopal,Shri K. C.','INC','Alappuzha(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (70,'Hassan,Dr. Monazir','JD(U)','Begusarai(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (71,'Jagathrakshakan,Shri S.','DMK','Arakkonam (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (72,'Nirupam,Shri Sanjay','INC','Mumbai-North(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (73,'Panda,Shri Prabodh','CPI','Medinipur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (74,'Dome,Dr. Ram Chandra','CPI(M)','Bolpur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (75,'Azharuddin,Shri Mohammed','INC','Moradabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (76,'Solanki ,Shri Dinubhai Boghabhai','BJP','Junagadh (Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (77,'Singh,Shri Ijyaraj','INC','Kota(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (78,'Verma,Shri Beni Prasad','INC','Gonda(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (79,'Rao,Shri Inderjit Singh','INC','Gurgaon (Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (80,'Ramasubbu,Shri S.S.','INC','Tirunelveli (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (81,'Singh,Shri Ajit','RLD','Baghpat(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (82,'Ajmal,Maulana Badruddin','AIUDF','Dhubri(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (83,'Malik,Shri Jitender Singh','INC','Sonipat(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (84,'Tanwar,Shri Ashok','INC','Sirsa(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (85,'Swaraj,Smt. Sushma','BJP','Vidisha(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (86,'Lingam,Shri P.','CPI','Tenkasi(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (87,'Pala,Shri Vincent H','INC','Shillong(Meghalaya )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (88,'Mohammad,Maulana Asrarul Haque','INC','Kishanganj (Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (89,'Deo,Shri V. Kishore Chandra','INC','Araku(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (90,'Lagadapati,Shri Rajagopal','INC','Vijayawada(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (91,'Rao,Shri Kalva Kuntla Chandrasek','TRS','Mahabubnagar (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (92,'Patel,Shri Praful Manoharbhai','NCP','Bhandara-Gondiya(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (93,'Sai,Shri Vishnu Deo','BJP','Raigarh (Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (94,'Majhi,Shri Pradeep','INC','Nabarangpur(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (95,'Bhonsle,Shri Udayanraje Pratapsi','NCP','Satara(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (96,'Dhotre,Shri Sanjay Shamrao','BJP','Akola(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (97,'Virendra Kumar,Dr.','BJP','Tikamgarh(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (98,'Babar ,Shri Gajanan Dharmshi','SS','Maval(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (99,'Solanki,Shri Makhansingh','BJP','Khargone(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (100,'Deka,Shri Ramen','BJP','Mangaldoi(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (101,'Engti,Shri Biren Singh','INC','Autonomous District(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (102,'Karwariya,Shri Kapil Muni','BSP','Phulpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (103,'Tirath,Smt. Krishna','INC','North West Delhi(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (104,'Shivakumar ,Shri K. alias J.K. R','DMK','Ramanathapuram(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (105,'Muniyappa,Shri K.H.','INC','Kolar(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (106,'Adhi Sankar,Shri','DMK','Kallakurichi(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (107,'Tharoor,Dr. Shashi','INC','Thiruvananthapuram(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (108,'Jindal,Shri Naveen','INC','Kurukshetra(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (109,'Mahato,Shri Narahari','AIFB','Purulia(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (110,'Bhoi,Shri Sanjay','INC','Bargarh(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (111,'Balmiki,Shri Kamlesh','SP','Bulandshahr(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (112,'Rajesh,Shri M. B.','CPI(M)','Palakkad (Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (113,'Shariq,Shri Sharifuddin','J&KNC','Baramulla(Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (114,'Riyan,Shri Baju Ban','CPI(M)','Tripura East(Tripura )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (115,'Gandhi,Shri Feroze Varun','BJP','Pilibhit (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (116,'Thambidurai,Dr. Munisamy','AIADMK','Karur(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (117,'Baitha,Shri Kameshwar','JMM','Palamu(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (118,'Rao,Shri Nama Nageswara','TDP','Khammam(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (119,'Suman,Shri Kabir','AITC','Jadavpur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (120,'Bavaliya,Shri Kunwarjibhai Mohan','INC','Rajkot (Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (121,'Patil,Shri Chandrakant Raghunath','BJP','Navsari (Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (122,'Rane,Dr. Nilesh Narayan','INC','Ratnagiri-Sindhudurg(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (123,'Danve,Shri Raosaheb Patil','BJP','Jalna (Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (124,'Jeyadurai,Shri S. R.','DMK','Thoothukkudi(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (125,'Roy,Shri Nripendra Nath','AIFB','Coochbehar(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (126,'Muttemwar,Shri Vilas Baburao','INC','Nagpur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (127,'Singh, Smt. Rajesh Nandini','INC','Shahdol(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (128,'Maadam,Shri Vikrambhai Arjanbhai','INC','Jamnagar(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (129,'Yadav,Shri Om Prakash','Ind.','Siwan(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (130,'Baba,Shri K.C. Singh','INC','Nainital-Udhamsingh Nagar(Uttarakhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (131,'Kumar,Smt. Meira','INC','Sasaram(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (132,'Hussain,Shri Ismail','INC','Barpeta(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (133,'Saroj,Smt. Sushila','SP','Mohanlalganj(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (134,'Satpathy,Shri Tathagata','BJD','Dhenkanal(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (135,'Chowdhury,Shri Adhir Ranjan','INC','Baharampur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (136,'Nahata,Smt. P. Jaya Prada','SP','Rampur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (137,'Singh,Shri Radhe Mohan','SP','Ghazipur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (138,'Biju,Shri Parayamparanbil Kuttap','CPI(M)','Alathur(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (139,'Dhanapalan,Shri K. P.','INC','Chalakudy(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (140,'Sarvey,Shri Sathyanarayana','INC','Malkajgiri(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (141,'Suresh,Shri Doddaalahalli Kempeg','INC','Bangalore Rural(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (142,'Jat,Smt. Poonam Veljibhai','BJP','Kachchh(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (143,'Botcha ,Dr. (Smt.) Jhansi Lakshm','INC','Vizianagaram(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (144,'Sayeed,Shri Hamdullah','INC','Lakshadweep(Lakshadweep )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (145,'Chitthan,Shri N.S.V.','INC','Dindigul(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (146,'Tandon,Shri Lal Ji','BJP','Lucknow(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (147,'Mahajan,Smt. Sumitra','BJP','Indore(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (148,'Sardinha,Shri Francisco','INC','South Goa(Goa )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (149,'Naik,Dr. Sanjeev Ganesh','NCP','Thane(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (150,'Baite,Shri Thangso','INC','Outer Manipur(Manipur )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (151,'Yadav, Prof. Ranjan Prasad','JD(U)','Pataliputra(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (152,'Laguri,Shri Yashbant Narayan Sin','BJD','Keonjhar(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (153,'Munda,Shri Kariya','BJP','Khunti(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (154,'Karunakaran,Shri P.','CPI(M)','Kasaragod(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (155,'Kumar,Shri Ramesh','INC','South Delhi(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (156,'Singh,Shri Mahabali','JD(U)','Karakat(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (157,'Raghavan,Shri M. K.','INC','Kozhikode (Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (158,'Kumar,Shri P.','AIADMK','Tiruchirappalli(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (159,'Sharma,Shri Madan Lal','INC','Jammu (Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (160,'Purandeswari,Smt. Daggubati','INC','Visakhapatnam(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (161,'Naqvi,Shri Zafar Ali','INC','Kheri (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (162,'Pandey,Shri Gorakh Nath','BSP','Bhadohi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (163,'Kachhadia,Shri Naranbhai','BJP','Amreli (Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (164,'Singh,Shri Ratanjit Pratap Narai','INC','Kushi Nagar(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (165,'Baske,Dr. Pulin Bihari','CPI(M)','Jhargram (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (166,'Patasani,Dr. (Prof.) Prasanna Ku','BJD','Bhubaneswar(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (167,'Rawat,Shri Harish','INC','Hardwar(Uttarakhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (168,'Venugopal,Dr. Ponnusamy','AIADMK','Tiruvallur(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (169,'Ahamed,Shri E.','IUML','Malappuram(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (170,'Manian,Shri O. S.','AIADMK','Mayiladuthurai(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (171,'Potai,Shri Sohan','BJP','Kanker(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (172,'Singh,Rajkumari Ratna','INC','Pratapgarh(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (173,'Kalmadi,Shri Suresh','INC','Pune(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (174,'Antony,Shri Anto','INC','Pathanamthitta(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (175,'Toppo,Shri Joseph','AGP','Tezpur(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (176,'Basavaraj,Shri Gangasandra Sidda','BJP','Tumkur(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (177,'Rao,Shri Konakalla Narayana','TDP','Machilipatnam(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (178,'Mohapatra,Shri Sidhant','BJD','Berhampur (Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (179,'Patel,Shri Natubhai Gomanbhai','BJP','Dadra and Nagar Haveli(Dadra and Nagar Haveli )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (180,'Rama Devi,Smt.','BJP','Sheohar(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (181,'Yadav,Shri M. Anjan Kumar','INC','Secunderabad(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (182,'Verma,Smt. Usha','SP','Hardoi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (183,'Patle,Smt. Kamla Devi','BJP','Janjgir-Champa(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (184,'Adhalrao Patil,Shri Shivaji','SS','Shirur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (185,'Aron,Shri Praveen Singh.','INC','Bareilly(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (186,'Prabhakar,Shri Ponnam','INC','Karimnagar(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (187,'Gandhi,Shri Dilip Kumar Mansukhl','BJP','Ahmednagar(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (188,'Thomas,Prof. Kuruppassery Varkey','INC','Ernakulam(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (189,'Raja,Shri Andimuthu','DMK','Nilgiris (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (190,'Nagar,Shri Surendra Singh','BSP','Gautam Buddha Nagar(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (191,'Sudhakaran,Shri Kumbakudi','INC','Kannur(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (192,'Pradhan,Shri Amarnath','INC','Sambalpur(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (193,'Aaroon Rasheed,Shri J.M.','INC','Theni(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (194,'Owaisi,Shri Asaduddin','AIMIM','Hyderabad(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (195,'Choudhary,Shri Harish','INC','Barmer(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (196,'Takam Sanjoy,Shri','INC','Arunachal West(Arunachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (197,'Tudu,Shri Laxman','BJD','Mayurbhanj(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (198,'Paranjpe,Shri Anand Prakash','SS','Kalyan(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (199,'Haldar,Dr. Sucharu Ranjan','AITC','Ranaghat (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (200,'Devegowda,Shri H.D.','JD(S)','Hassan(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (201,'Perumal,Shri Viswanathan','INC','Kancheepuram(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (202,'Udasi,Shri Shivkumar Chanabasapp','BJP','Haveri(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (203,'Hegde,Shri Anant Kumar Dattatrey','BJP','Uttara Kannada(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (204,'Jagannath,Dr. M.','INC','Nagarkurnool(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (205,'Rana ,Shri Rajendrasinh (Raju Ra','BJP','Bhavnagar(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (206,'Gawali (Patil),Ms. Bhavana','SS','Yavatmal-Washim(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (207,'Kurup,Shri N. Peethambara','INC','Kollam(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (208,'Patel,Shri Dinsha J.','INC','Kheda(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (209,'Thamaraiselvan,Shri R.','DMK','Dharmapuri(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (210,'Singh Deo,Shri Kalikesh Narayan','BJD','Bolangir(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (211,'Abdul Rahman,Shri','DMK','Vellore(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (212,'Mani,Shri Jose K.','KC(M)','Kottayam(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (213,'Reddy,Shri Modugula Venugopala','TDP','Narasaraopet (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (214,'Narayanasamy,Shri V.','INC','Puducherry(Puducherry )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (215,'Sushant,Dr. Rajan','BJP','Kangra(Himachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (216,'Patil ,Dr. Padmasinha Bajirao','NCP','Osmanabad(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (217,'Adsul,Shri Anandrao','SS','Amravati(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (218,'Bhuria,Shri Kantilal','INC','Ratlam(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (219,'Gaddigoudar,Shri Parvatagouda Ch','BJP','Bagalkot(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (220,'Rathwa,Shri Ramsinh Patalyabhai','BJP','Chhota Udaipur (Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (221,'Amlabe,Shri Narayan Singh','INC','Rajgarh(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (222,'Hari,Shri Sabbam','INC','Anakapalli(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (223,'Jawale,Shri Haribhau Madhav','BJP','Raver(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (224,'Angadi,Shri Suresh Chanabasappa','BJP','Belgaum(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (225,'Vasava,Shri Mansukhbhai D.','BJP','Bharuch(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (226,'Sahu,Shri Chandu Lal','BJP','Mahasamund (Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (227,'Taware ,Shri Suresh Kashinath','INC','Bhiwandi(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (228,'Reddy,Shri Komatireddy Raj Gopal','INC','Bhongir(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (229,'Shetti ,Shri Raju alias Devappa ','SWP','Hatkanangle(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (230,'Shantha,Smt. J.','BJP','Bellary (Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (231,'Tagore,Shri Manicka','INC','Virudhunagar(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (232,'Mahto,Shri Baidyanath Prasad','JD(U)','Valmiki Nagar(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (233,'Geete,Shri Anant Gangaram','SS','Raigad (Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (234,'Jadhav ,Shri Baliram Sukur','BVA','Palghar(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (235,'Gandhiselvan,Shri S.','DMK','Namakkal(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (236,'Patel,Shri Kishanbhai Vestabhai','INC','Valsad(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (237,'Dhurve,Smt. Jyoti','BJP','Betul(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (238,'Malik,Shri Sakti Mohan','CPI(M)','Arambagh (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (239,'Trivedi,Shri Dinesh','AITC','Barrackpur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (240,'Reddy,Shri S.P.Y.','INC','Nandyal(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (241,'Singh,Shri Rakesh','BJP','Jabalpur(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (242,'Kodikunnil,Shri Suresh','INC','Mavelikkara(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (243,'Swamy,Shri Janardhana','BJP','Chitradurga(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (244,'Adityanath ,Shri Yogi','BJP','Gorakhpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (245,'Singh,Dr. Raghuvansh Prasad','RJD','Vaishali(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (246,'Ahmed,Shri Sultan','AITC','Uluberia(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (247,'Naik,Shri Porika Balram','INC','Mahabubabad(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (248,'Rao,Shri Rayapati Sambasiva','INC','Guntur (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (249,'Jatua,Shri Choudhury Mohan','AITC','Mathurapur (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (250,'Krishnasswamy,Shri M.','INC','Arani(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (251,'Semmalai,Shri S.','AIADMK','Salem(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (252,'Harsha Kumar,Shri G.V.','INC','Amalapuram(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (253,'Ganeshamurthi,Shri A.','MDMK','Erode(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (254,'Ghubaya,Shri Sher Singh','SAD','Ferozpur(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (255,'Reddy,Shri Mekapati Rajamohan','YSR Congress Party','Nellore(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (256,'Tomar,Shri Narendra Singh','BJP','Morena(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (257,'Kataria,Shri Lalchand','INC','Jaipur Rural (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (258,'Singh,Shri Jitendra','INC','Alwar(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (259,'Bali Ram,Dr.','BSP','Lalganj(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (260,'Baalu,Thiru Thalikkottai Rajuthe','DMK','Sriperumbudur(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (261,'Chauhan,Shri Prabhatsinh Prataps','BJP','Panchmahal(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (262,'Naskar,Shri Gobinda Chandra','AITC','Bangaon(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (263,'Singh,Smt. Pratibha','INC','Mandi(Himachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (264,'Tamta,Shri Pradeep','INC','Almora(Uttarakhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (265,'Solanki,Dr. Kirit Premjibhai','BJP','Ahmedabad West(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (266,'Tarai,Shri Bibhu Prasad','CPI','Jagatsinghpur(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (267,'Jena,Shri Srikant Kumar','INC','Balasore(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (268,'Pandey,Dr. Vinay Kumar "Vinnu"','INC','Shrawasti(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (269,'Ray,Shri Bishnu Pada','BJP','Andaman and Nicobar Islands(Andaman and Nicobar Islands )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (270,'Gandhi,Shri Rahul','INC','Amethi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (271,'Patel,Smt. Jayshreeben','BJP','Mahesana(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (272,'Pandey,Km. Saroj','BJP','Durg (Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (273,'Babbar,Shri Raj','INC','Firozabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (274,'Shanthi,Smt. M. Vijaya','TRS','Medak (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (275,'Kanumuri,Shri Bapi Raju','INC','Narsapuram(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (276,'Sivasami,Shri C.','AIADMK','Tiruppur(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (277,'Singh,Shri Sushil Kumar','JD(U)','Aurangabad(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (278,'Jigajinagi,Shri Ramesh Chandappa','BJP','Bijapur(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (279,'Haque,Prof. Sk. Saidul','CPI(M)','Bardhaman-Durgapur(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (280,'Sule,Smt. Supriya Sadanand','NCP','Baramati(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (281,'Basheer,Shri E. T. Mohammed','IUML','Ponnani (Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (282,'Yadav,Shri Sharad','JD(U)','Madhepura(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (283,'Mandal,Shri Mangani Lal','JD(U)','Jhanjharpur(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (284,'Yadav,Shri Dinesh Chandra','JD(U)','Khagaria(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (285,'Yadav,Shri Ramakant','BJP','Azamgarh(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (286,'Thakor,Shri Jagdish','INC','Patan(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (287,'Sahai,Shri Subodh Kant','INC','Ranchi(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (288,'Lal,Shri Pakauri','SP','Robertsganj (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (289,'Saroj,Shri Tufani','SP','Machhlishahr(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (290,'Singh,Shri Ganesh','BJP','Satna(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (291,'Patel,Shri R.K. Singh','SP','Banda(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (292,'Siddeshwara,Shri Gowdar Mallikar','BJP','Davanagere(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (293,'Awale ,Shri Jayawant Gangaram','INC','Latur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (294,'Vyas,Dr.(Kum.) Girija','INC','Chittorgarh(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (295,'Singh,Shri Rajnath','BJP','Ghaziabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (296,'Thol,Shri Thirumaa Valavan','VCK','Chidambaram(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (297,'Barq,Shri Shafiqur Rahman','BSP','Sambhal(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (298,'Acharia,Shri Basudeb','CPI(M)','Bankura(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (299,'Singh,Shri Pashupati Nath','BJP','Dhanbad(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (300,'Sivaprasad,Dr. Naramalli','TDP','Chittoor(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (301,'Joshi,Shri Kailash','BJP','Bhopal(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (302,'Jena,Shri Mohan','BJD','Jajpur (Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (303,'Singh,Shri Jagadanand','RJD','Buxar(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (304,'Sinha,Shri Shatrughan Prasad','BJP','Patna Sahib(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (305,'Dasmunsi,Smt. Deepa','INC','Raiganj(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (306,'Bansal,Shri Pawan Kumar','INC','Chandigarh(Chandigarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (307,'Singh,Shri Dhananjay','BSP','Jaunpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (308,'Helen, Smt. Davidson J.','DMK','Kanniyakumari(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (309,'Pathak,Shri Harin','BJP','Ahmedabad East(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (310,'Chaudhary,Shri Haribhai Parthibh','BJP','Banaskantha(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (311,'Kharge,Shri Mallikarjun','INC','Gulbarga (Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (312,'Ananth Kumar,Shri','BJP','Bangalore South(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (313,'Sampath,Shri Anirudhan','CPI(M)','Attingal(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (314,'Patil,Shri Bhaskarrao Bapurao','INC','Nanded(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (315,'Bakshi,Shri Subrata','AITC','Kolkata Dakshin(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (316,'Natrajan,Km. Meenakshi','INC','Mandsour(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (317,'Mohan,Shri P. C.','BJP','Bangalore Central(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (318,'Sangma,Kum. Agatha K.','NCP','Tura(Meghalaya )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (319,'Kumar,Shri Shailendra','SP','Kaushambi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (320,'Chauhan,Shri Dara Singh','BSP','Ghosi(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (321,'Chaudhary,Shri Arvind Kumar','BSP','Basti (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (322,'Badal,Smt. Harsimrat Kaur','SAD','Bathinda(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (323,'Mirdha,Dr. (Smt.) Jyoti','INC','Nagaur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (324,'Joshi,Dr. C. P.','INC','Bhilwara(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (325,'Mishra,Shri Mahabal','INC','West Delhi(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (326,'Rai,Shri Prem Das','SDF','Sikkim(Sikkim )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (327,'Dhruvanarayana,Shri Rangaswamy','INC','Chamrajanagar(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (328,'Reddy,Shri Anantha Venkatarami','INC','Anantapur (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (329,'Bais,Shri Ramesh','BJP','Raipur(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (330,'Mishra,Shri Govind Prasad','BJP','Sidhi (Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (331,'Paul,Shri Tapas','AITC','Krishnanagar(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (332,'Ramkishun,Shri','SP','Chandauli(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (333,'Vundavalli,Shri Aruna Kumar','INC','Rajahmundry(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (334,'Roy,Prof. Saugata','AITC','Dum Dum(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (335,'Rajendran,Shri C.','AIADMK','Chennai South(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (336,'Paswan,Shri Kamlesh','BJP','Bansgaon(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (337,'Sibal,Shri Kapil','INC','Chandni Chowk(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (338,'Shetkar,Shri Suresh Kumar','INC','Zahirabad(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (339,'Baghel,Smt. Sarika Devendra Sing','RLD','Hathras(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (340,'Patel,Shri Somabhai Gandalal Kol','INC','Surendranagar(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (341,'Kaswan,Shri Ram Singh','BJP','Churu (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (342,'Kumar,Dr. (Shri) Ajay','JVM (P)','Jamshedpur(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (343,'Pandey,Shri Rakesh','BSP','Ambedkar Nagar (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (344,'Palanimanickam,Shri S.S.','DMK','Thanjavur (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (345,'Dikshit,Shri Sandeep','INC','East Delhi(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (346,'Pangi,Shri Jayaram','BJD','Koraput (Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (347,'Yeddyurappa,Shri Raghavendra','BJP','Shimoga(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (348,'Yadav,Shri Madhusudan','BJP','Rajnandgaon(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (349,'Shah,Smt. Mala Rajya Laxmi','BJP','Tehri Garhwal(Uttarakhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (350,'Verma,Shri Sajjan Singh','INC','Dewas(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (351,'Gowda,Shri Chandre D.B.','BJP','Bangalore North(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (352,'Dias,Dr. Charles','INC','Nominated Anglo-Indian(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (353,'Gandhi,Smt. Maneka Sanjay','BJP','Aonla(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (354,'Rana,Shri Jagdish Singh','BSP','Saharanpur (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (355,'Dutt,Smt. Priya Sunil','INC','Mumbai-North-Central(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (356,'Elangovan,Shri T.K.S.','DMK','Chennai North(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (357,'Patel,Shri Lalubhai Babubhai','BJP','Daman and Diu(Daman and Diu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (358,'Raju ,Dr. M. Mangapati Pallam','INC','Kakinada (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (359,'Singh,Shri Radha Mohan','BJP','Purvi Champaran(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (360,'Taviad,Dr. (Smt.) Prabha Kishor','INC','Dahod(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (361,'Kishor,Shri Kamal','INC','Bahraich (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (362,'Guddu,Shri Prem Chand','INC','Ujjain(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (363,'Das,Shri Khagen','CPI(M)','Tripura West(Tripura )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (364,'Shinde,Shri Sushil Kumar Sambhaj','INC','Solapur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (365,'Beg,(Dr.) Mirza Mehboob','J&KNC','Anantnag(Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (366,'Upadhyay,Smt. Seema','BSP','Fatehpur Sikri(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (367,'Kashyap,Shri Virender','BJP','Shimla(Himachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (368,'Siricilla,Shri Rajaiah','INC','Warangal(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (369,'De(Nag),Dr. (Smt.) Ratna','AITC','Hooghly(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (370,'Pilot,Shri Sachin','INC','Ajmer (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (371,'Mahtab,Shri Bhartruhari','BJD','Cuttack(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (372,'Jain Aditya ,Shri Pradeep Kumar','INC','Jhansi (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (373,'Patil,Shri Pratik Prakashbapu','INC','Sangli(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (374,'Dudhgaonkar,Shri Ganeshrao Nagor','SS','Parbhani(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (375,'Jakhar,Shri Badri Ram','INC','Pali(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (376,'Patil,Shri A.T. (Nana)','BJP','Jalgaon(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (377,'Namdhari,Shri Inder Singh','Ind.','Chatra(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (378,'Singh,Shri Ravneet','INC','Anandpur Sahib(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (379,'Shukla ,Shri Balkrishna Khandera','BJP','Vadodara(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (380,'Singh,Shri Dushyant','BJP','Jhalawar-Baran (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (381,'Joshi,Dr. Mahesh','INC','Jaipur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (382,'Chidambaram,Shri Palaniappan','INC','Sivaganga(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (383,'Sethi,Shri Arjun Charan','BJD','Bhadrak(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (384,'Reddy,Shri Kotla Jaya Surya Prak','INC','Kurnool(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (385,'Devi,Smt. Ashwamedh','JD(U)','Ujiarpur(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (386,'Adhikari ,Shri Sisir Kumar','AITC','Kanthi(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (387,'Annayyagari,Shri Sai Prathap','INC','Rajampet(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (388,'Maharaj,Shri Satpal','INC','Garhwal(Uttarakhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (389,'Pakkirappa,Shri S.','BJP','Raichur (Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (390,'Ram Shankar,Prof.(Dr.)','BJP','Agra(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (391,'Shanavas,Shri M. I.','INC','Wayanad(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (392,'Bundela,Shri Jeetendra Singh','BJP','Khajuraho (Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (393,'Bishnoi,Shri Kuldeep','HJC','Hisar(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (394,'Khandela,Shri Mahadeo Singh','INC','Sikar (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (395,'Jaiswal,Shri Gorakh Prasad','BSP','Deoria (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (396,'Jaiswal,Shri Sriprakash','INC','Kanpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (397,'Patel,Shri Devji Mansingram','BJP','Jalore(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (398,'Wasnik,Shri Mukul Balkrishna','INC','Ramtek(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (399,'Chacko,Shri P.C.','INC','Thrissur(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (400,'Napoleon,Shri D.','DMK','Perambalur(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (401,'Tiwari ,Shri Bhismshankar Alias ','BSP','Sant Kabir Nagar(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (402,'Rao,Dr. Kavuri Samba Siva','INC','Eluru(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (403,'Agrawal,Shri Rajendra','BJP','Meerut(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (404,'Kaur,Smt. Preneet','INC','Patiala(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (405,'Choudhry,Smt. Shruti','INC','Bhiwani-Mahendragarh (Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (406,'Naik,Shri Shripad Yesso','BJP','North Goa(Goa )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (407,'Singh,Kunwar Rewati Raman','SP','Allahabad(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (408,'Chowdhary,Smt. Santosh','INC','Hoshiarpur(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (409,'Kamat,Shri Gurudas','INC','Mumbai-North-West(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (410,'Roy,Smt. Satabdi','AITC','Birbhum(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (411,'Panabaka,Smt. Lakshmi','INC','Bapatla (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (412,'Mandlik,Shri Sadashivrao Dadoba','Ind.','Kolhapur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (413,'Chakravarty,Smt. Bijoya','BJP','Gauhati(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (414,'Lodhi,Shri Shivraj Singh','BJP','Damoh (Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (415,'Hazari,Shri Maheshwar','JD(U)','Samastipur (Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (416,'Bhujbal,Shri Sameer Magan','NCP','Nashik(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (417,'Chauhan,Shri Sanjay Singh','RLD','Bijnor (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (418,'Meinya,Dr. Thokchom','INC','Inner Manipur(Manipur )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (419,'Sharma,Dr. Arvind Kumar','INC','Karnal(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (420,'Hossain,Shri Abdul Mannan','INC','Murshidabad (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (421,'Reddy,Shri Magunta Sreenivasulu','INC','Ongole (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (422,'Noor,Smt. Mausam','INC','Maldaha Uttar(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (423,'Hegde,Shri Jayaprakash Korgi','INC','Udupi Chikmagalur(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (424,'Sidhu,Shri Navjot Singh','BJP','Amritsar(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (425,'Rathod,Shri Ramesh','TDP','Adilabad (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (426,'Bhagat,Shri Sudarshan','BJP','Lohardaga (Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (427,'Abdullah,Dr. Farooq','J&KNC','Srinagar(Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (428,'Pal ,Shri Jagdambika','INC','Domariyaganj (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (429,'Katti,Shri Ramesh Vishwanath','BJP','Chikkodi(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (430,'Singh,Shri Vijay Bahadur','BSP','Hamirpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (431,'Alagiri,Shri Sambandam Keerapala','INC','Cuddalore(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (432,'Misra,Shri Pinaki','BJD','Puri (Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (433,'Thakur,Shri Anurag Singh','BJP','Hamirpur(Himachal Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (434,'Gavit,Shri Manikrao Hodlya','INC','Nandurbar(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (435,'Narah,Smt. Ranee','INC','Lakhimpur (Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (436,'Chauhan,Dr. Mahendrasinh Pruthvi','BJP','Sabarkantha(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (437,'Dasgupta,Shri Gurudas','CPI','Ghatal(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (438,'Kowase,Shri Marotrao Sainuji','INC','Gadchiroli-Chimur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (439,'Venugopal,Thiru Danapal','DMK','Tiruvannamalai(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (440,'Mithlesh Kumar,Shri','SP','Shahjahanpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (441,'Sinha,Shri Yashwant','BJP','Hazaribagh(Jharkhand )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (442,'Libra,Shri Sukhdev Singh','INC','Fatehgarh Sahib(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (443,'Mullappally,Shri Ramachandran','INC','Vadakara (Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (444,'Kaypee,Shri Mohinder Singh','INC','Jalandhar(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (445,'Advani,Shri Lal Krishna','BJP','Gandhinagar(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (446,'Radadiyahai,Shri Vitthalbhai Han','BJP','Porbandar(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (447,'Singh,Shri Uday','BJP','Purnia(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (448,'Rana,Shri Kadir','BSP','Muzaffarnagar (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (449,'Shekhar,Shri Neeraj','SP','Ballia (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (450,'Meghe,Shri Datta Raghobaji','INC','Wardha(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (451,'Agarwal,Shri Jai Prakash','INC','North East Delhi(Delhi )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (452,'Ahir,Shri Hansraj Gangaram','BJP','Chandrapur(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (453,'Chinta Mohan,Dr.','INC','Tirupati(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (454,'Islam,Shri Sk. Nurul','AITC','Basirhat(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (455,'Sugavanam,Shri E.G.','DMK','Krishnagiri(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (456,'Tandon,Smt. Annu','INC','Unnao(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (457,'Putul Kumari,Smt.','Ind.','Banka(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (458,'Yadav,Shri Hukmdev Narayan','BJP','Madhubani(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (459,'Nishad,Capt.(Retd.) Jainarain Pr','JD(U)','Muzaffarpur(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (460,'Pradhan,Shri Nityananda','BJD','Aska(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (461,'Kamal Nath,Shri','INC','Chhindwara (Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (462,'Kashyap,Shri Dinesh','BJP','Bastar(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (463,'Killi,Dr. (Smt.) Kruparani','INC','Srikakulam (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (464,'Tirkey,Shri Manohar','RSP','Alipurduars(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (465,'Singh,Shri Prabhunath','RJD','Maharajganj(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (466,'Pal,Shri Raja Ram','INC','Akbarpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (467,'Yadav,Shri Mulayam Singh','SP','Mainpuri(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (468,'Ray,Shri Rudra Madhab','BJD','Kandhamal(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (469,'Dastidar, Dr. (Smt.) Kakoli Ghos','AITC','Barasat(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (470,'Nimmala,Shri Kristappa','TDP','Hindupur (Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (471,'Jadhav,Shri Prataprao Ganpatrao','SS','Buldhana(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (472,'Gohain,Shri Rajen','BJP','Nawgong(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (473,'Solanki,Shri Bharatsinh Madhavsi','INC','Anand(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (474,'Das,Shri Bhakta Charan','INC','Kalahandi(Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (475,'Rawat,Shri Ashok Kumar','BSP','Misrikh (Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (476,'Joshi,Shri Pralhad Venkatesh','BJP','Dharwad (Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (477,'Masram,Shri Basori Singh','INC','Mandla(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (478,'Jaiswal,Dr. Sanjay','BJP','Paschim Champaran(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (479,'Prasada,Shri Jitin','INC','Dhaurahra(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (480,'Spandana,Km. Ramya Divya','INC','Mandya(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (481,'Vivekanand,Dr. Gaddam','INC','Peddapalle(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (482,'Handique,Shri Bijoy Krishna','INC','Jorhat(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (483,'Biswal,Shri Hemanand','INC','Sundargarh (Odisha )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (484,'Suklabaidya,Shri Lalit Mohan','INC','Karimganj(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (485,'Vardhan,Shri Harsh','INC','Maharajganj(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (486,'Sugumar,Shri K.','AIADMK','Pollachi(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (487,'Singla,Shri Vijay Inder','INC','Sangrur(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (488,'Deora,Shri Milind Murli','INC','Mumbai-South(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (489,'Maran,Thiru Dayanidhi','DMK','Chennai Central (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (490,'Choudhary,Shri Nikhil Kumar','BJP','Katihar(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (491,'Ghatowar,Shri Paban Singh','INC','Dibrugarh(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (492,'Kateel,Shri Nalin Kumar','BJP','Dakshina Kannada (Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (493,'Tewari,Shri Manish','INC','Ludhiana(Punjab )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (494,'Gandhi,Smt. Sonia','INC','Rae Bareli(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (495,'Bandyopadhyay,Shri Sudip','AITC','Kolkata Uttar(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (496,'Khan,Shri Hassan','Ind.','Ladakh(Jammu and Kashmir )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (497,'Rajukhedi,Shri Gajendra Singh','INC','Dhar(Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (498,'Munde ,Shri Gopinath Pandurang','BJP','Beed(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (499,'Thomas,Shri P. T.','INC','Idukki(Kerala )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (500,'Anandan,Shri K. Murugesan','AIADMK','Viluppuram(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (501,'Hussain,Shri Syed Shahnawaz','BJP','Bhagalpur(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (502,'Singh,Shri Yashvir','SP','Nagina(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (503,'Mahant,Dr. Charan Das','INC','Korba(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (504,'Purkayastha,Shri Kabindra','BJP','Silchar(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (505,'Vishwanath,Shri Adagooru Huchego','INC','Mysore(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (506,'Yaskhi,Shri Madhu Goud','INC','Nizamabad(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (507,'Vijayan,Shri A.K.S.','DMK','Nagapattinam(Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (508,'Adhikari,Shri Suvendu','AITC','Tamluk(West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (509,'Anuragi,Shri Ghanshyam','SP','Jalaun(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (510,'Gogoi,Shri Dip','INC','Kaliabor(Assam )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (511,'Bhadana,Shri Avtar Singh','INC','Faridabad(Haryana )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (512,'Chaudhary,Dr. Tushar Amarsinh','INC','Bardoli(Gujarat )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (513,'Meghwal,Shri Arjun Ram','BJP','Bikaner (Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (514,'Sachan,Shri Rakesh','SP','Fatehpur(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (515,'Natarajan,Shri P.R.','CPI(M)','Coimbatore (Tamil Nadu )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (516,'Reddy,Shri Y. S. Jagan Mohan','YSR Congress Party','Kadapa(Andhra Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (517,'Pratap Narayanrao,Shri Sonawane','BJP','Dhule(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (518,'Mcleod,Smt. Ingrid','INC','Nominated Anglo-Indian(Chhattisgarh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (519,'Meena,Shri Namo Narain','INC','Tonk-Sawai Madhopur(Rajasthan )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (520,'Ruala,Shri C. L.','INC','Mizoram(Mizoram )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (521,'Singh,Shri N.Dharam','INC','Bidar(Karnataka )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (522,'Chavan,Shri Harischandra Deoram','BJP','Dindori(Maharashtra )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (523,'Hasan,Begum Tabassum','BSP','Kairana(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (524,'Chaudhary,Shri Jayant','RLD','Mathura(Uttar Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (525,'Singh,Shri Pradeep Kumar','BJP','Araria(Bihar )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (526,'Patel,Shri Deoraj Singh','BSP','Rewa (Madhya Pradesh )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (527,'Mitra,Shri Somendra Nath','AITC','Diamond Harbour (West Bengal )');
INSERT INTO `loksabha_15_members`(`id`,`name`,`party_name`,`constituency`) VALUES (528,'Roy,Shri Mahendra Kumar','CPI(M)','Jalpaiguri (West Bengal )');
