CREATE TABLE if not exists`loksabha_15_531` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`name` varchar(40) not NULL,
	`imageurl` varchar(256) DEFAULT NULL,
	`mothername` varchar(40) DEFAULT NULL,
	`dateofbirth` varchar(20) DEFAULT NULL,
	`placeofbirth` varchar(64) NOT NULL,
	`education` varchar(256) DEFAULT NULL,
	`maritalstatus` varchar(14) DEFAULT NULL,
	`spousename` varchar(40) DEFAULT NULL,  
	`marriagedate` varchar(20) DEFAULT NULL,
	`noofdaughters` varchar(2) DEFAULT NULL,
	`noofsons` varchar(2) DEFAULT NULL,
	`partyname` varchar(64) not NULL,
	`profession` varchar(128) DEFAULT NULL,
	`constituency` varchar(128) default NULL,
	`presentaddress` varchar(256) DEFAULT NULL,
	`permanentaddress` varchar(256) DEFAULT NULL,
	`emailid` varchar(40) DEFAULT NULL,
	`countriesvisited` blob DEFAULT NULL,
	`positionsheld` varchar(256) DEFAULT NULL,
	`otherinformation` blob DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

